package com.DS.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzJobDetails<M extends BaseQrtzJobDetails<M>> extends Model<M> implements IBean {

	public void setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public void setJobName(java.lang.String jobName) {
		set("JOB_NAME", jobName);
	}
	
	public java.lang.String getJobName() {
		return getStr("JOB_NAME");
	}

	public void setJobGroup(java.lang.String jobGroup) {
		set("JOB_GROUP", jobGroup);
	}
	
	public java.lang.String getJobGroup() {
		return getStr("JOB_GROUP");
	}

	public void setDESCRIPTION(java.lang.String DESCRIPTION) {
		set("DESCRIPTION", DESCRIPTION);
	}
	
	public java.lang.String getDESCRIPTION() {
		return getStr("DESCRIPTION");
	}

	public void setJobClassName(java.lang.String jobClassName) {
		set("JOB_CLASS_NAME", jobClassName);
	}
	
	public java.lang.String getJobClassName() {
		return getStr("JOB_CLASS_NAME");
	}

	public void setIsDurable(java.lang.String isDurable) {
		set("IS_DURABLE", isDurable);
	}
	
	public java.lang.String getIsDurable() {
		return getStr("IS_DURABLE");
	}

	public void setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("IS_NONCONCURRENT", isNonconcurrent);
	}
	
	public java.lang.String getIsNonconcurrent() {
		return getStr("IS_NONCONCURRENT");
	}

	public void setIsUpdateData(java.lang.String isUpdateData) {
		set("IS_UPDATE_DATA", isUpdateData);
	}
	
	public java.lang.String getIsUpdateData() {
		return getStr("IS_UPDATE_DATA");
	}

	public void setRequestsRecovery(java.lang.String requestsRecovery) {
		set("REQUESTS_RECOVERY", requestsRecovery);
	}
	
	public java.lang.String getRequestsRecovery() {
		return getStr("REQUESTS_RECOVERY");
	}

	public void setJobData(byte[] jobData) {
		set("JOB_DATA", jobData);
	}
	
	public byte[] getJobData() {
		return get("JOB_DATA");
	}

}
