package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPId(java.lang.String pId) {
		set("pId", pId);
	}
	
	public java.lang.String getPId() {
		return getStr("pId");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setOpen(java.lang.String open) {
		set("open", open);
	}
	
	public java.lang.String getOpen() {
		return getStr("open");
	}

	public void setChecked(java.lang.String checked) {
		set("checked", checked);
	}
	
	public java.lang.String getChecked() {
		return getStr("checked");
	}

}
