package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDsRemind<M extends BaseDsRemind<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRemindName(java.lang.String remindName) {
		set("remindName", remindName);
	}
	
	public java.lang.String getRemindName() {
		return getStr("remindName");
	}

	public void setRemindText(java.lang.String remindText) {
		set("remindText", remindText);
	}
	
	public java.lang.String getRemindText() {
		return getStr("remindText");
	}

	public void setRemindTime(java.util.Date remindTime) {
		set("remindTime", remindTime);
	}
	
	public java.util.Date getRemindTime() {
		return get("remindTime");
	}

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}
	
	public java.lang.String getMail() {
		return getStr("mail");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}
	
	public java.util.Date getAddTime() {
		return get("addTime");
	}

}
