package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setWarnFlag(java.lang.String warnFlag) {
		set("warn_flag", warnFlag);
	}
	
	public java.lang.String getWarnFlag() {
		return getStr("warn_flag");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setWarnItem(java.lang.String warnItem) {
		set("warn_item", warnItem);
	}
	
	public java.lang.String getWarnItem() {
		return getStr("warn_item");
	}

}
