package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzSchedulerState<M extends BaseQrtzSchedulerState<M>> extends Model<M> implements IBean {

	public void setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public void setInstanceName(java.lang.String instanceName) {
		set("INSTANCE_NAME", instanceName);
	}
	
	public java.lang.String getInstanceName() {
		return getStr("INSTANCE_NAME");
	}

	public void setLastCheckinTime(java.lang.Long lastCheckinTime) {
		set("LAST_CHECKIN_TIME", lastCheckinTime);
	}
	
	public java.lang.Long getLastCheckinTime() {
		return getLong("LAST_CHECKIN_TIME");
	}

	public void setCheckinInterval(java.lang.Long checkinInterval) {
		set("CHECKIN_INTERVAL", checkinInterval);
	}
	
	public java.lang.Long getCheckinInterval() {
		return getLong("CHECKIN_INTERVAL");
	}

}
