package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEcharts<M extends BaseEcharts<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCategories(java.lang.String categories) {
		set("categories", categories);
	}
	
	public java.lang.String getCategories() {
		return getStr("categories");
	}

	public void setData(java.lang.Integer data) {
		set("data", data);
	}
	
	public java.lang.Integer getData() {
		return getInt("data");
	}

}
