package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnalyse<M extends BaseAnalyse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setFunction(java.lang.String function) {
		set("function", function);
	}
	
	public java.lang.String getFunction() {
		return getStr("function");
	}

	public void setAnalyseType(java.lang.String analyseType) {
		set("analyseType", analyseType);
	}
	
	public java.lang.String getAnalyseType() {
		return getStr("analyseType");
	}

}
