package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialtree<M extends BaseMaterialtree<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOwnNode(java.lang.String ownNode) {
		set("own_node", ownNode);
	}
	
	public java.lang.String getOwnNode() {
		return getStr("own_node");
	}

	public void setParentNode(java.lang.String parentNode) {
		set("parent_node", parentNode);
	}
	
	public java.lang.String getParentNode() {
		return getStr("parent_node");
	}

	public void setMaterialName(java.lang.String materialName) {
		set("material_name", materialName);
	}
	
	public java.lang.String getMaterialName() {
		return getStr("material_name");
	}

}
