package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotification<M extends BaseNotification<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setSender(java.lang.String sender) {
		set("sender", sender);
	}
	
	public java.lang.String getSender() {
		return getStr("sender");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}
	
	public java.lang.String getSubject() {
		return getStr("subject");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setOperatetime(java.util.Date operatetime) {
		set("operatetime", operatetime);
	}
	
	public java.util.Date getOperatetime() {
		return get("operatetime");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public void setReadFlag(java.lang.Integer readFlag) {
		set("readFlag", readFlag);
	}
	
	public java.lang.Integer getReadFlag() {
		return getInt("readFlag");
	}

	public void setCreateType(java.lang.Integer createType) {
		set("createType", createType);
	}
	
	public java.lang.Integer getCreateType() {
		return getInt("createType");
	}

}
