package com.DS.common.model;

import com.DS.common.model.base.BaseMaterialtree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Materialtree extends BaseMaterialtree<Materialtree> {
	
}
