package com.DS.common.model;

import com.DS.common.model.base.BaseNotification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notification extends BaseNotification<Notification> {
	
}
