package com.DS.common.model;

import com.DS.common.model.base.BaseProjectTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectTree extends BaseProjectTree<ProjectTree> {
	
}
