package com.DS.common.model;

import com.DS.common.model.base.BaseThEarlywarningRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThEarlywarningRule extends BaseThEarlywarningRule<ThEarlywarningRule> {
	
}
