package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEarlyWarningRule<M extends BaseEarlyWarningRule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setEarlyWarningName(java.lang.String earlyWarningName) {
		set("early_warning_name", earlyWarningName);
	}
	
	public java.lang.String getEarlyWarningName() {
		return getStr("early_warning_name");
	}

	public void setEarlyWarningType(java.lang.String earlyWarningType) {
		set("early_warning_type", earlyWarningType);
	}
	
	public java.lang.String getEarlyWarningType() {
		return getStr("early_warning_type");
	}

	public void setEarlyWarningTransactor(java.lang.String earlyWarningTransactor) {
		set("early_warning_transactor", earlyWarningTransactor);
	}
	
	public java.lang.String getEarlyWarningTransactor() {
		return getStr("early_warning_transactor");
	}

	public void setMaterialType(java.lang.String materialType) {
		set("material_type", materialType);
	}
	
	public java.lang.String getMaterialType() {
		return getStr("material_type");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public void setMax(java.lang.Long max) {
		set("max", max);
	}
	
	public java.lang.Long getMax() {
		return getLong("max");
	}

	public void setMin(java.lang.Long min) {
		set("min", min);
	}
	
	public java.lang.Long getMin() {
		return getLong("min");
	}

}
