package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzSimpleTriggers<M extends BaseQrtzSimpleTriggers<M>> extends Model<M> implements IBean {

	public void setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public void setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public void setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public void setRepeatCount(java.lang.Long repeatCount) {
		set("REPEAT_COUNT", repeatCount);
	}
	
	public java.lang.Long getRepeatCount() {
		return getLong("REPEAT_COUNT");
	}

	public void setRepeatInterval(java.lang.Long repeatInterval) {
		set("REPEAT_INTERVAL", repeatInterval);
	}
	
	public java.lang.Long getRepeatInterval() {
		return getLong("REPEAT_INTERVAL");
	}

	public void setTimesTriggered(java.lang.Long timesTriggered) {
		set("TIMES_TRIGGERED", timesTriggered);
	}
	
	public java.lang.Long getTimesTriggered() {
		return getLong("TIMES_TRIGGERED");
	}

}
