package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzTriggers<M extends BaseQrtzTriggers<M>> extends Model<M> implements IBean {

	public void setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public void setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public void setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public void setJobName(java.lang.String jobName) {
		set("JOB_NAME", jobName);
	}
	
	public java.lang.String getJobName() {
		return getStr("JOB_NAME");
	}

	public void setJobGroup(java.lang.String jobGroup) {
		set("JOB_GROUP", jobGroup);
	}
	
	public java.lang.String getJobGroup() {
		return getStr("JOB_GROUP");
	}

	public void setDESCRIPTION(java.lang.String DESCRIPTION) {
		set("DESCRIPTION", DESCRIPTION);
	}
	
	public java.lang.String getDESCRIPTION() {
		return getStr("DESCRIPTION");
	}

	public void setNextFireTime(java.lang.Long nextFireTime) {
		set("NEXT_FIRE_TIME", nextFireTime);
	}
	
	public java.lang.Long getNextFireTime() {
		return getLong("NEXT_FIRE_TIME");
	}

	public void setPrevFireTime(java.lang.Long prevFireTime) {
		set("PREV_FIRE_TIME", prevFireTime);
	}
	
	public java.lang.Long getPrevFireTime() {
		return getLong("PREV_FIRE_TIME");
	}

	public void setPRIORITY(java.lang.Integer PRIORITY) {
		set("PRIORITY", PRIORITY);
	}
	
	public java.lang.Integer getPRIORITY() {
		return getInt("PRIORITY");
	}

	public void setTriggerState(java.lang.String triggerState) {
		set("TRIGGER_STATE", triggerState);
	}
	
	public java.lang.String getTriggerState() {
		return getStr("TRIGGER_STATE");
	}

	public void setTriggerType(java.lang.String triggerType) {
		set("TRIGGER_TYPE", triggerType);
	}
	
	public java.lang.String getTriggerType() {
		return getStr("TRIGGER_TYPE");
	}

	public void setStartTime(java.lang.Long startTime) {
		set("START_TIME", startTime);
	}
	
	public java.lang.Long getStartTime() {
		return getLong("START_TIME");
	}

	public void setEndTime(java.lang.Long endTime) {
		set("END_TIME", endTime);
	}
	
	public java.lang.Long getEndTime() {
		return getLong("END_TIME");
	}

	public void setCalendarName(java.lang.String calendarName) {
		set("CALENDAR_NAME", calendarName);
	}
	
	public java.lang.String getCalendarName() {
		return getStr("CALENDAR_NAME");
	}

	public void setMisfireInstr(java.lang.Integer misfireInstr) {
		set("MISFIRE_INSTR", misfireInstr);
	}
	
	public java.lang.Integer getMisfireInstr() {
		return getInt("MISFIRE_INSTR");
	}

	public void setJobData(byte[] jobData) {
		set("JOB_DATA", jobData);
	}
	
	public byte[] getJobData() {
		return get("JOB_DATA");
	}

}
