package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseThEarlywarningOrder<M extends BaseThEarlywarningOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setEarlywarningItems(java.lang.String earlywarningItems) {
		set("earlywarning_items", earlywarningItems);
	}
	
	public java.lang.String getEarlywarningItems() {
		return getStr("earlywarning_items");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setFreezeId(java.lang.Long freezeId) {
		set("freeze_id", freezeId);
	}
	
	public java.lang.Long getFreezeId() {
		return getLong("freeze_id");
	}

	public void setFreezeTime(java.util.Date freezeTime) {
		set("freeze_time", freezeTime);
	}
	
	public java.util.Date getFreezeTime() {
		return get("freeze_time");
	}

}
