package com.DS.common.model;

import com.DS.common.model.base.BaseEarlyWarningRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EarlyWarningRule extends BaseEarlyWarningRule<EarlyWarningRule> {
	
}
