package com.DS.common.model;

import com.DS.common.model.base.BaseQrtzCronTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzCronTriggers extends BaseQrtzCronTriggers<QrtzCronTriggers> {
	
}
