package com.DS.common.model;

import com.DS.common.model.base.BaseQrtzSchedulerState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzSchedulerState extends BaseQrtzSchedulerState<QrtzSchedulerState> {
	
}
