package com.DS.common.model;

import com.DS.common.model.base.BaseQrtzTriggers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzTriggers extends BaseQrtzTriggers<QrtzTriggers> {
	
}
