package com.DS.common.model;

import com.DS.common.model.base.BaseQrtzJobDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrtzJobDetails extends BaseQrtzJobDetails<QrtzJobDetails> {
	
}
