package com.DS.common.model;

import com.DS.common.model.base.BaseThEarlywarningOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ThEarlywarningOrder extends BaseThEarlywarningOrder<ThEarlywarningOrder> {
	
}
