package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZtree<M extends BaseZtree<M>> extends Model<M> implements IBean {

	public void setLogicalId(java.lang.Integer logicalId) {
		set("logicalId", logicalId);
	}
	
	public java.lang.Integer getLogicalId() {
		return getInt("logicalId");
	}

	public void setTaskId(java.lang.Integer taskId) {
		set("taskId", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("taskId");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setPId(java.lang.String pId) {
		set("pId", pId);
	}
	
	public java.lang.String getPId() {
		return getStr("pId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

}
