package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenuInfo<M extends BaseMenuInfo<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.Integer menuId) {
		set("MENU_ID", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("MENU_ID");
	}

	public void setPMenuId(java.lang.Integer pMenuId) {
		set("p_menu_id", pMenuId);
	}
	
	public java.lang.Integer getPMenuId() {
		return getInt("p_menu_id");
	}

	public void setSubsysCode(java.lang.String subsysCode) {
		set("SUBSYS_CODE", subsysCode);
	}
	
	public java.lang.String getSubsysCode() {
		return getStr("SUBSYS_CODE");
	}

	public void setMenuName(java.lang.String menuName) {
		set("MENU_NAME", menuName);
	}
	
	public java.lang.String getMenuName() {
		return getStr("MENU_NAME");
	}

	public void setMenuPath(java.lang.String menuPath) {
		set("MENU_PATH", menuPath);
	}
	
	public java.lang.String getMenuPath() {
		return getStr("MENU_PATH");
	}

	public void setMenuComment(java.lang.String menuComment) {
		set("MENU_COMMENT", menuComment);
	}
	
	public java.lang.String getMenuComment() {
		return getStr("MENU_COMMENT");
	}

	public void setRemoveTag(java.lang.Boolean removeTag) {
		set("REMOVE_TAG", removeTag);
	}
	
	public java.lang.Boolean getRemoveTag() {
		return get("REMOVE_TAG");
	}

	public void setCheckAuth(java.lang.Boolean checkAuth) {
		set("CHECK_AUTH", checkAuth);
	}
	
	public java.lang.Boolean getCheckAuth() {
		return get("CHECK_AUTH");
	}

	public void setDisplay(java.lang.Boolean display) {
		set("display", display);
	}
	
	public java.lang.Boolean getDisplay() {
		return get("display");
	}

	public void setHierarchy(java.lang.Integer hierarchy) {
		set("hierarchy", hierarchy);
	}
	
	public java.lang.Integer getHierarchy() {
		return getInt("hierarchy");
	}

	public void setMenuType(java.lang.Boolean menuType) {
		set("menu_type", menuType);
	}
	
	public java.lang.Boolean getMenuType() {
		return get("menu_type");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

	public void setSortNo(java.lang.Integer sortNo) {
		set("sort_no", sortNo);
	}
	
	public java.lang.Integer getSortNo() {
		return getInt("sort_no");
	}

	public void setAddDate(java.util.Date addDate) {
		set("ADD_DATE", addDate);
	}
	
	public java.util.Date getAddDate() {
		return get("ADD_DATE");
	}

	public void setOperUser(java.lang.Long operUser) {
		set("OPER_USER", operUser);
	}
	
	public java.lang.Long getOperUser() {
		return getLong("OPER_USER");
	}

	public void setOperTime(java.util.Date operTime) {
		set("OPER_TIME", operTime);
	}
	
	public java.util.Date getOperTime() {
		return get("OPER_TIME");
	}

	public void setSysId(java.lang.String sysId) {
		set("SYS_ID", sysId);
	}
	
	public java.lang.String getSysId() {
		return getStr("SYS_ID");
	}

}
