package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderItem<M extends BaseOrderItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRefOrderId(java.lang.Integer refOrderId) {
		set("ref_order_id", refOrderId);
	}
	
	public java.lang.Integer getRefOrderId() {
		return getInt("ref_order_id");
	}

	public void setMaterialName(java.lang.String materialName) {
		set("material_name", materialName);
	}
	
	public java.lang.String getMaterialName() {
		return getStr("material_name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setAmount(java.lang.Long amount) {
		set("amount", amount);
	}
	
	public java.lang.Long getAmount() {
		return getLong("amount");
	}

	public void setRefMaterialId(java.lang.Integer refMaterialId) {
		set("ref_material_id", refMaterialId);
	}
	
	public java.lang.Integer getRefMaterialId() {
		return getInt("ref_material_id");
	}

}
