package com.DS.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQrtzFiredTriggers<M extends BaseQrtzFiredTriggers<M>> extends Model<M> implements IBean {

	public void setSchedName(java.lang.String schedName) {
		set("SCHED_NAME", schedName);
	}
	
	public java.lang.String getSchedName() {
		return getStr("SCHED_NAME");
	}

	public void setEntryId(java.lang.String entryId) {
		set("ENTRY_ID", entryId);
	}
	
	public java.lang.String getEntryId() {
		return getStr("ENTRY_ID");
	}

	public void setTriggerName(java.lang.String triggerName) {
		set("TRIGGER_NAME", triggerName);
	}
	
	public java.lang.String getTriggerName() {
		return getStr("TRIGGER_NAME");
	}

	public void setTriggerGroup(java.lang.String triggerGroup) {
		set("TRIGGER_GROUP", triggerGroup);
	}
	
	public java.lang.String getTriggerGroup() {
		return getStr("TRIGGER_GROUP");
	}

	public void setInstanceName(java.lang.String instanceName) {
		set("INSTANCE_NAME", instanceName);
	}
	
	public java.lang.String getInstanceName() {
		return getStr("INSTANCE_NAME");
	}

	public void setFiredTime(java.lang.Long firedTime) {
		set("FIRED_TIME", firedTime);
	}
	
	public java.lang.Long getFiredTime() {
		return getLong("FIRED_TIME");
	}

	public void setSchedTime(java.lang.Long schedTime) {
		set("SCHED_TIME", schedTime);
	}
	
	public java.lang.Long getSchedTime() {
		return getLong("SCHED_TIME");
	}

	public void setPRIORITY(java.lang.Integer PRIORITY) {
		set("PRIORITY", PRIORITY);
	}
	
	public java.lang.Integer getPRIORITY() {
		return getInt("PRIORITY");
	}

	public void setSTATE(java.lang.String STATE) {
		set("STATE", STATE);
	}
	
	public java.lang.String getSTATE() {
		return getStr("STATE");
	}

	public void setJobName(java.lang.String jobName) {
		set("JOB_NAME", jobName);
	}
	
	public java.lang.String getJobName() {
		return getStr("JOB_NAME");
	}

	public void setJobGroup(java.lang.String jobGroup) {
		set("JOB_GROUP", jobGroup);
	}
	
	public java.lang.String getJobGroup() {
		return getStr("JOB_GROUP");
	}

	public void setIsNonconcurrent(java.lang.String isNonconcurrent) {
		set("IS_NONCONCURRENT", isNonconcurrent);
	}
	
	public java.lang.String getIsNonconcurrent() {
		return getStr("IS_NONCONCURRENT");
	}

	public void setRequestsRecovery(java.lang.String requestsRecovery) {
		set("REQUESTS_RECOVERY", requestsRecovery);
	}
	
	public java.lang.String getRequestsRecovery() {
		return getStr("REQUESTS_RECOVERY");
	}

}
